apiVersion: apps/v1
kind: Deployment
metadata: 
  name: shop-deploy
  namespace: aws9d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop 
  template:  
    metadata:
      labels:
        app: shop
    spec:
      initContainers:
        - name: init-html
          image: busybox
          command:
            - /bin/sh
            - -c
            - echo "<html><body><h1>SHOP PAGE</h1></body></html>" > /shared/index.html
          volumeMounts:
            - name: html
              mountPath: /shared
      containers:
        - name: aws9ctn-shop
          image: hub.aws9.pri/toytest1/aws9:shop
          resources:
            requests:
              cpu: "100m"
            limits: 
              cpu: "200m"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: shop-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-shop
  namespace: aws9d
spec:
  ports:
  - name: aws9-port-shop
    port: 80      
    targetPort: 80   
  selector:
    app: shop
