apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blog-deploy
  namespace: aws9d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog  
  template:  
    metadata:
      labels:
        app: blog
    spec:
      initContainers:
        - name: init-html
          image: busybox
          command:
            - /bin/sh
            - -c
            - echo "<html><body><h1>BLOG PAGE</h1></body></html>" > /shared/index.html
          volumeMounts:
            - name: html
              mountPath: /shared
      containers:
        - name: aws9ctn-blog
          image: hub.aws9.pri/toytest1/aws9:blog
          resources:
            requests:
              cpu: "100m"
            limits: 
              cpu: "200m"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: blog-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-blog
  namespace: aws9d
spec:
  ports:
  - name: aws9-port-blog
    port: 80      
    targetPort: 80   
  selector:
    app: blog
